
name: lint

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ ci_cd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          pip install flake8-html
          # pip install mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # pip install -r event-api/requirements/api.txt
          
      - name: Lint with wemake-python-styleguide
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./event-api/src/app --count --select=E9,F63,F7,F82 --show-source --statistics --format=html --htmldir=flake-report
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./event-api/src/app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --format=html --htmldir=flake-report
      - name: Upload linter HTML report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Linter HTML report
          path: flake-report
          if-no-files-found: ignore
      - name: mypy checks
        run: |
          mkdir ./event-api/src/app/.mypy_cache
          pip install mypy
          mypy --install-types --non-interactive ./event-api/src/app
